### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Cavorter** [strdn/rundeck-jdbc-executor-plugin#1]
I'm certain I'm doing something wrong, but I copied the plugin jar to libext, a copy of groovy-sql-2.4.11.jar to bootstrap, and a copy of mssql-jdbc-6.2.2.jre8.jar also to bootstrap. The plugin does not show up in my plugins page even after a restart of the service or a restart of the whole machine. Other plugins seem to be loading just fine. I'm not seeing any errors in any logs. (CentOS 7, Rundeck 2.10.3) Any ideas?

**Comment by strdn** [comment]
Hello. I cannot reproduce this problem.
Tried with CentOS 7, RunDeck 2.10.3 and oracle java 1.8.0_131
The plugin appears in the list of plugins as "Groovy SQL command executor", are you sure that it is not there? Does the rundeck-user have a read permissions to the plugin jar?
