### ISSUE TITLE
where is the boostrap location? 

### ISSUE THREAD

**Issue by beepony** [strdn/rundeck-jdbc-executor-plugin#10]
Hi, I got trouble in installing the plugin, I did't find the boostrap directory in rundeck, can you tell me boostrap location please , thanks very much ~

![image](https://user-images.githubusercontent.com/7813288/71443327-4c076080-2745-11ea-9b3d-beef95caf890.png)

Here is my rundeck directory 

```
[18:40:48 /usr/local/rundeck]
$ ls
etc                 libext    repository                  rundeck-jdbc-executor-plugin  server  user-assets
hs_err_pid3140.log  projects  rundeck-3.1.3-20191204.war  run.log

```

**Comment by strdn** [comment]
Hello!
Please try to see here:
```
$ cd /var/lib/rundeck/
$ ls
bootstrap  cli  data  exp  libext  logs  var  work
```

**Comment by strdn** [comment]
Hello!
Please try to see in the `rdeck.base` directory:
```
$ grep "rdeck.base" /etc/rundeck/rundeck-config.properties
rdeck.base=/var/lib/rundeck
$ cd /var/lib/rundeck
$ ls
bootstrap  cli  data  exp  libext  logs  var  work
```

**Comment by wtt20182018** [comment]
hi ， I come across the same problem. Don't have any dir named bootstrap.`$ grep "rdeck.base" rundeck-config.properties
rdeck.base=/data/project/rundeck
$ cd /data/project/rundeck
$ ls
etc  libext  projects  repository  rundeck-3.2.0-20191218.war  server  tools  user-assets  var`

**Comment by beepony** [comment]
> hi ， I come across the same problem. Don't have any dir named bootstrap.
> 
> `$ grep "rdeck.base" rundeck-config.properties
> rdeck.base=/data/project/rundeck
> 
> $ cd /data/project/rundeck
> 
> $ ls
> etc libext projects repository rundeck-3.2.0-20191218.war server tools user-assets var`

I downgrade the 2.8.3 version solved the probloem ～

**Comment by strdn** [comment]
OK, I'll see in the next few days how this should work on version 3.2

**Comment by strdn** [comment]
HI :) New plugin version compatible with Rundeck 3.3.x (tested with rundeck 3.3.7). Please take a look at new installation step desc: https://github.com/strdn/rundeck-jdbc-executor-plugin#install
