### ISSUE TITLE
Error Unknown database type:null

### ISSUE THREAD

**Issue by ext94053** [strdn/rundeck-jdbc-executor-plugin#11]
Describe the bug
I create job with rundeck-jdbc-executor-plugin but not working

My Rundeck detail

Rundeck version: 3.2.8
install type: jar
OS Name/version: Red Hat Linux 6
DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]
To Reproduce

Install Plugin
Copy ojdbc6.jar and groovy-sql-2.4.11.jar in tools/lib
Create Job with step "Groovy sql script executor"
Execute the job

The error is Failed: ConfigurationFailure: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: Unknown database type:null

**Comment by strdn** [comment]
it looks like you forgot to configure the remote host, please see https://github.com/strdn/rundeck-jdbc-executor-plugin#configuration

**Comment by ext94053** [comment]
Hi

Now the error is the following

Failed: ConfigurationFailure: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: jdbc driver class not foundoracle.jdbc.driver.OracleDriver

I create the boostrap folder and copy insiste groovy-sql-2.4.11.jar  ojdbc6.jar

Is correct?

Thanks a lot

**Comment by strdn** [comment]
With Rundeck 3.3.x and new plugin version groovy jar's and jdbc driver must be added to the `lib/` directory.  
(`${RDECK_BASE}/lib` is for WAR, TOMCAT, and `/var/lib/rundeck/lib` is for RPM, DEB.)
