### ISSUE TITLE
jdbc driver class not foundoracle.jdbc.driver.OracleDriver

### ISSUE THREAD

**Issue by Ein-nor** [strdn/rundeck-jdbc-executor-plugin#13]
Hello,

it looks like I have a configuration problem.

My Rundeck Details:
Rundeck version: 3.4.0
Install type: WAR with Tomcat 9.0.39 with AdoptOpenJDK 11.0.10+9
OS Name/version: Red Hat Linux 7.8
DB Type/version: postgresql

I've downloaded the plugin and put it to $RDECK_BASE/libext.
I've also created a folder $RDECK_BASE/lib an put the following files into this folder:
- groovy-jsr223-3.0.8.jar
- groovy-sql-3.0.8.jar
- ojdbc8.jar (tested also ojdbc10.jar)

My Node Configuration:
`<?xml version="1.0" encoding="UTF-8"?>
<project>
  <node name="SERVERNAME" node-executor="jdbc-command" db-type="oracle" jdbc-connect="jdbc:oracle:thin:@ SERVERNAME:1521:ORACLESID" jdbc-username="system" jdbc-password="password" description="" tags="" hostname="SERVERNAME" osArch="amd64" osFamily="unix" osName="Linux" osVersion="" username="root"/>
</project>
`

Rundeck Job Log Output:
`[workflow] beginExecuteNodeStep(cg1-mstrdb-t301): NodeDispatch: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
Failed: ConfigurationFailure: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: jdbc driver class not foundoracle.jdbc.driver.OracleDriver
[workflow] finishExecuteNodeStep(cg1-mstrdb-t301): NodeDispatch: ConfigurationFailure: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: jdbc driver class not foundoracle.jdbc.driver.OracleDriver`

**Comment by eagle-rr** [comment]
You might want to take a look at bottom of: https://github.com/strdn/rundeck-jdbc-executor-plugin/issues/12 .  It looks like the war install library path is $RDECK_BASE/server/lib (not just $RDECK_BASE/lib which is for rpm-based installation).
