### ISSUE TITLE
Wrong DBType for MySQL database

### ISSUE THREAD

**Issue by eric-sy2377** [strdn/rundeck-jdbc-executor-plugin#3]
你好，我在使用过程中，发现你有一个bug，在/src/main/java/com/github/strdn/rundeck/plugin/jdbcexecutor/DBTypes.java里面，传入oracle和mysql都是返回oracle
public static DBTypes getDBType(String databaseName) {
        if (oracleDatabase.equalsIgnoreCase(databaseName))
            return ORACLE;
        if (mysqlDatabase.equalsIgnoreCase(databaseName))
            return ORACLE;
        if (postgresDatabase.equalsIgnoreCase(databaseName))
            return POSTGRES;
        return UNKNOWN;
}

**Comment by strdn** [comment]
Fixed in latest build. The version number has not changed.
