### ISSUE TITLE
Feature request: Parameterize connection parameters (allow use of secrets or job options)

### ISSUE THREAD

**Issue by babs** [strdn/rundeck-jdbc-executor-plugin#6]
Node information are publicly available to one who has access to rundeck interface or api, therefore, db, user and password are available.

It would be nice if informations like password, username or database coule also be sourced from the job argument mechanism or maybe step arguments like script args that, if empty fall back to the actual mechanism.
This would allow the use of key storage mechanism and thus parameterize DSN and protect secret. 

Another option would be less user friendly but to pass DSN as argument (maybe w/ the driver class name ?) and initialize connection inside the groovy script ?

**Comment by strdn** [comment]
Hi!
You can specify node keystore path using parameter "jdbc-password-storage-path", please see https://github.com/strdn/rundeck-jdbc-executor-plugin/blob/37b741928ed31044ec51870bfe295b7d6187b218/src/main/java/com/github/strdn/rundeck/plugin/jdbcexecutor/SqlConnectionBuilder.java#L64
It's not enough?

**Comment by babs** [comment]
It works quite nicely, it deserve to be mentioned in the readme :)

**Comment by strdn** [comment]
Added in https://github.com/strdn/rundeck-jdbc-executor-plugin/pull/7
