### ISSUE TITLE
jdbc-password-storage-path setting sample

### ISSUE THREAD

**Issue by dadayoo** [strdn/rundeck-jdbc-executor-plugin#8]
Hi
i want hide jdbc-password at rundeck node page 
can provide a samlpe set of jdbc-password-storage-path  configure and keyfile content ?
thanks!

**Comment by strdn** [comment]
Hi @babs!
Can you provide example, please? #6 
Unfortunately, I do not have a working installation at hand.

**Comment by babs** [comment]
Hi @strdn @dadayoo,
To make it work, simply add, as node attribute, something like the following example (exact format depend on your resource structure) and add a key of type password in your key storage with the according path (in this very case, local/mysql-test).

```
db-type=mysql
jdbc-password-storage-path=keys/local/mysql-test
jdbc-username=test
jdbc-connect=jdbc:mysql://localhost/test
```

**Comment by strdn** [comment]
@babs, keyfile must contain only one string with the password, right? (I have not used Rundesk for about a year, sorry)

**Comment by babs** [comment]
It's nit a key file, it's an entry in the key storage of type "Password" (3 types available: pubkey, privkey,password)

**Comment by dadayoo** [comment]
@babs `jdbc-password-storage-path=keys/local/mysql-test`
`mysql-test ` this file only one string with the password ?
like: `password="mysqlpassword"`
can you provide content of `mysql-test` ?
thanks ~

**Comment by babs** [comment]
Please read carefully replies.
It's not a file, it uses the key storage mechanism of rundeck.
Top right icon of rundeck, Key storage then add a Password type entry.
I can add screenshots later it you ditn't find it.

**Comment by dadayoo** [comment]
@babs emm...sorry , i didn't find it
could you show more detail? screenshot will be great!
i just want to hidden my database password on rundeck node page

**Comment by babs** [comment]
Mileage may vary depending on your version, but the idea is the same:

![RD01-2019-09-01_12-39](https://user-images.githubusercontent.com/117580/64075227-ee429a80-ccb5-11e9-8341-f10742fccd25.png)
![RD02-2019-09-01_12-39](https://user-images.githubusercontent.com/117580/64075228-ee429a80-ccb5-11e9-9045-cd112d157413.png)
![RD03-2019-09-01_12-40](https://user-images.githubusercontent.com/117580/64075229-ee429a80-ccb5-11e9-83fb-5a250a0e2043.png)
![RD04-2019-09-01_12-41](https://user-images.githubusercontent.com/117580/64075230-ee429a80-ccb5-11e9-80fc-56b6fed5a98e.png)

**Comment by dadayoo** [comment]
@babs that's work well ! thanks a lot !
